from PyQt6 import QtCore, QtGui, QtWidgets


class LineXAndOtherTasksWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 469)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 70, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.taskLine = QtWidgets.QLabel(parent=self.centralwidget)
        self.taskLine.setGeometry(QtCore.QRect(230, 210, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.taskLine.setFont(font)
        self.taskLine.setText("")
        self.taskLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.taskLine.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.taskLine.setObjectName("taskLine")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 350, 47, 13))
        self.label_9.setObjectName("label_9")
        self.answerLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.answerLine.setGeometry(QtCore.QRect(90, 350, 211, 20))
        self.answerLine.setObjectName("answerLine")
        self.answer_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.answer_btn.setGeometry(QtCore.QRect(740, 350, 75, 23))
        self.answer_btn.setObjectName("answer_btn")
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(670, 380, 141, 23))
        self.exit_btn.setObjectName("exit_btn")
        self.verdictLine = QtWidgets.QLabel(parent=self.centralwidget)
        self.verdictLine.setGeometry(QtCore.QRect(320, 350, 411, 21))
        self.verdictLine.setText("")
        self.verdictLine.setObjectName("verdictLine")
        self.flagLine = QtWidgets.QLabel(parent=self.centralwidget)
        self.flagLine.setGeometry(QtCore.QRect(40, 380, 251, 16))
        self.flagLine.setText("")
        self.flagLine.setObjectName("flagLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Линейное уравнение"))
        self.label.setText(_translate("MainWindow", "Задание Линейное уравнение"))
        self.label_2.setText(_translate("MainWindow", "Задача: Решите линейное уравнение."))
        self.label_3.setText(_translate("MainWindow", "Введите только число - корень уравнения(решение примера), если он дробный, то сократите до сотых."))
        self.label_9.setText(_translate("MainWindow", "Ответ:"))
        self.answer_btn.setText(_translate("MainWindow", "Ответить"))
        self.exit_btn.setText(_translate("MainWindow", "Выйти в главное меню"))
