from PyQt6 import QtCore, QtGui, QtWidgets


class MenuWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 470)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 671, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 100, 441, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 140, 211, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 190, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.square_x_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.square_x_btn.setGeometry(QtCore.QRect(40, 230, 141, 23))
        self.square_x_btn.setObjectName("square_x_btn")
        self.line_x_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.line_x_btn.setGeometry(QtCore.QRect(40, 260, 141, 23))
        self.line_x_btn.setObjectName("line_x_btn")
        self.sum_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sum_btn.setGeometry(QtCore.QRect(40, 290, 141, 23))
        self.sum_btn.setObjectName("sum_btn")
        self.min_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.min_btn.setGeometry(QtCore.QRect(40, 320, 141, 23))
        self.min_btn.setObjectName("min_btn")
        self.crop_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.crop_btn.setGeometry(QtCore.QRect(40, 380, 141, 23))
        self.crop_btn.setObjectName("crop_btn")
        self.mul_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mul_btn.setGeometry(QtCore.QRect(40, 350, 141, 23))
        self.mul_btn.setObjectName("mul_btn")
        self.easy_test_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.easy_test_btn.setGeometry(QtCore.QRect(470, 230, 141, 23))
        self.easy_test_btn.setObjectName("easy_test_btn")
        self.hard_test_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hard_test_btn.setGeometry(QtCore.QRect(470, 260, 141, 23))
        self.hard_test_btn.setObjectName("hard_test_btn")
        self.rating = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(630, 380, 71, 23))
        self.rating.setObjectName("rating")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 380, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задачник"))
        self.label.setText(_translate("MainWindow", "Задачник"))
        self.label_2.setText(_translate("MainWindow", "В этом приложении вы можете потренировать свои вычислительные навыки, решая примеры разных уровней сложности."))
        self.label_3.setText(_translate("MainWindow", "А также порешать квадратные и линейные уравнения. И даже целые тесты."))
        self.label_4.setText(_translate("MainWindow", "Выберите, что будете решать. Удачи!!!"))
        self.label_5.setText(_translate("MainWindow", "Тренировочные задания"))
        self.label_6.setText(_translate("MainWindow", "Тренировочные тесты"))
        self.square_x_btn.setText(_translate("MainWindow", "Квадратное уравнение"))
        self.line_x_btn.setText(_translate("MainWindow", "Линейное уравнение"))
        self.sum_btn.setText(_translate("MainWindow", "Пример на сложение"))
        self.min_btn.setText(_translate("MainWindow", "Пример на вычитание"))
        self.crop_btn.setText(_translate("MainWindow", "Пример на деление"))
        self.mul_btn.setText(_translate("MainWindow", "Пример на умножение"))
        self.easy_test_btn.setText(_translate("MainWindow", "Легкий тест"))
        self.hard_test_btn.setText(_translate("MainWindow", "Сложный тест"))
        self.label_7.setText(_translate("MainWindow", "ВАШ РЕЙТИНГ:"))
